version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/myproject/db.sqlite3:/app/myproject/db.sqlite3
      - ./backend/myproject/contact_1.db.sqlite3:/app/myproject/contact_1.db.sqlite3
      - ./backend/myproject/contact_v2.db.sqlite3:/app/myproject/contact_v2.db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONPATH=/app
      - APP_VERSION=${APP_VERSION}
    working_dir: /app/myproject
    restart: 'no'