services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/myproject:/app/myproject
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings  # Updated path
      - PYTHONPATH=/app/myproject 