services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ./backend/myproject/db.sqlite3:/app/myproject/db.sqlite3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge