services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VERSION=${VERSION}
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VERSION=${VERSION}
    volumes:
      - ./backend/myproject:/app/myproject  # Mount only the myproject/ directory  # Optional for development; consider removing for production
    networks:
      - mynetwork
    working_dir: /app/myproject

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb_${VERSION}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maanas6114
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge