services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - VERSION=${VERSION}
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VERSION=${VERSION}
    networks:
      - mynetwork
    working_dir: /app/myproject

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maanas6114
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge