version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONPATH=/app:/app/myproject
      - APP_VERSION=${APP_VERSION}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    working_dir: /app/myproject
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port for TCP checks
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=mypassword pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10

  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8082:80"
    volumes:
    - ./nagios/etc:/opt/nagios/etc
    - ./nagios/var:/opt/nagios/var
    environment:
      - NAGIOS_TIMEZONE=UTC
      - NAGIOS_ADMIN_USER=nagiosadmin
      - NAGIOS_ADMIN_PASSWORD=nagios
    user: root
    command: [ "/usr/local/bin/start_nagios" ]
    depends_on:
      - backend
      - db

volumes:
  postgres_data:
  nagios_data: