services:
  backend:
    build: ./backend
    volumes:
      - ./backend/myproject:/app/myproject  # Only mount the Django project directory
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
networks:
  mynetwork:
    driver: bridge