services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    networks:
      - mynetwork
    volumes:
      - ./backend/myproject/:/app/myproject/

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge