version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONPATH=/app
      - APP_VERSION=${APP_VERSION}
    working_dir: /app/myproject
    restart: unless-stopped