version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/myproject:/app  # Mount the correct directory
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=maanas6114
      - DJANGO_SUPERUSER_EMAIL=vslk.maanas@example.com
    working_dir: /app  # Ensure it starts from the correct working directory for manage.py

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
