services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"  # Change host port to 8001 to avoid conflicts
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge