version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONPATH=/app:/app/myproject
      - APP_VERSION=${APP_VERSION}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    working_dir: /app/myproject
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "com.nagios.enable=true"
      - "com.nagios.check_http=yes"
      - "com.nagios.http_port=8000"

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=mypassword pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - "com.nagios.enable=true"
      - "com.nagios.check_postgres=yes"
      - "com.nagios.db_user=myuser"
      - "com.nagios.db_pass=mypassword"

  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8082:80"
    volumes:
      - nagios_data:/opt/nagios/etc
      - ./nagios/custom:/opt/nagios/etc/objects/custom
    environment:
      - NAGIOS_TIMEZONE=UTC
      - NAGIOS_ADMIN_USER=nagiosadmin
      - NAGIOS_ADMIN_PASSWORD=nagios
    depends_on:
      - nrpe

  nrpe:
    image: jasonrivers/nagios-nrpe
    environment:
      - NAGIOS_SERVER=nagios
    volumes:
      - ./nagios/nrpe.cfg:/etc/nagios/nrpe.cfg
    links:
      - backend
      - db

volumes:
  postgres_data:
  nagios_data:
  nagios_var: