version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Remove this volume mount or make it more specific
    # volumes:
    #   - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - PYTHONPATH=/app
    working_dir: /app/myproject
    restart: unless-stopped