FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN chmod +x init-superuser.sh
EXPOSE 8000
CMD ["/bin/bash", "-c", "./init-superuser.sh && python myproject/manage.py runserver 0.0.0.0:8000"]